version: '3.8'

services:
  mockauth:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=dev
      - DATABASE_URL=postgresql://user:password@db:5432/mockauth
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mockauth
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres_data:
